Aggregate vocalics
ml4ai/tomcat-coordination pull request #4
Opened 2022-07-14 02:01 UTC by eduongAZ

2022-07-14 03:49 UTC, paulosoaresua requested changes

2022-07-14 03:49 UTC, paulosoaresua commented on src/components/speech/vocalics_aggregator.py
> +            if len(current_utterance.vocalic_series) == 0:
I don't understand this part. We want to keep adding vocalics until  current utterance overlaps with next utterance or ends before the next utterance starts. We will never have empty vocalics for an utterance since we agreed to ignore short utterances with no vocalics.

2022-07-14 03:49 UTC, paulosoaresua commented on src/components/speech/common.py
> -        # Equalizes the sizes of the two series
Did you fix the issue in the writer? I don't remember why I wrote this todo.

2022-07-14 03:49 UTC, paulosoaresua commented on src/components/speech/vocalics_aggregator.py
> +                    if next_utterance is not None and vocalics.timestamp > next_utterance.start:
Are you saving the vocalics timestamp relative to the utterance? If you use the timestamp from the database it's going to be wrong. We have to adjust it by the offset you computer in the last PR.

2022-07-14 16:48 UTC, eduongAZ commented on src/components/speech/vocalics_aggregator.py
> +            if len(current_utterance.vocalic_series) == 0:
We found that the short utterances are short replies, which signifies the end of the previous utterance. Let t be timestamp for utterance with no vocalics (short replies we want to ignore). If t-1 utterance is player Red and t+1 utterance is also player Red, it would be weird to concatenate utterance t-1 and t+1 simply because we ignore utterance t. I think we should end utterance t-1 first, then make t+1 a new segmented utterance.

2022-07-14 18:23 UTC, eduongAZ commented on src/components/speech/common.py
> -        # Equalizes the sizes of the two series
No, I moved it to `vocalics_writer.py`

2022-07-14 19:15 UTC, paulosoaresua requested changes

2022-07-14 19:15 UTC, paulosoaresua commented on src/components/speech/vocalics_aggregator.py
> +                if next_utterance is not None and vocalics.timestamp + self._timestamp_offset > next_utterance.start:
Instead of using the offset here, I would just save the vocalics timestamp discounted by the offset in the vocalics reader. This function does not have to know the vocalics in the table are shifted.

2022-07-14 20:27 UTC, eduongAZ commented on src/components/speech/vocalics_aggregator.py
> +                if next_utterance is not None and vocalics.timestamp + self._timestamp_offset > next_utterance.start:
I give vocalic readers a start timestamp for it to reset the vocalics timestamps to.

2022-07-15 03:44 UTC, paulosoaresua approved these changes

2022-07-15 03:44 UTC, paulosoaresua commented on src/components/speech/vocalics_aggregator.py
> +        utterances = list(filter(lambda u: len(u.vocalic_series) > 0, utterances))
This is good for now. You can merge this PR and create another one to do that only if the duration of the utterance is smaller than a threshold. We can define the threshold as a constant and set it to 1 second. If there are no vocalics for the utterance and its duration is larger than the threshold, we still remove it, but add to the log. We print the log list in the end to summarize if we any utterance fell into that rule.

2022-07-15 17:26 UTC, merged